package com.wipro.wess.ods.reporting;

import java.nio.charset.Charset;
import java.util.StringTokenizer;

import com.google.common.io.BaseEncoding;
import com.wipro.wess.ods.organisation.OrganisationPK;

// Generated Dec 19, 2013 5:56:26 PM by Hibernate Tools 3.2.2.GA

/**
 * OmLocationHierarchyId generated by hbm2java
 */
public class OmLocationHierarchyPK implements java.io.Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = 6103699810212263168L;

    public String locationUid;

    public OrganisationPK organisation;

    public OmLocationHierarchyPK(String key) {
        StringTokenizer token = new StringTokenizer(decode(key), "~");
        this.locationUid = token.nextToken();
        this.organisation = new OrganisationPK(token.nextToken());
    }

    @Override
    public String toString() {
        return encode("" + this.locationUid + "~" + this.organisation.toString());
    }

    public OmLocationHierarchyPK() {
    }

    public OmLocationHierarchyPK(String locationUid, OrganisationPK organisation) {
        this.locationUid = locationUid;
        this.organisation = organisation;
    }

    public String getLocationUid() {
        return this.locationUid;
    }

    public void setLocationUid(String locationUid) {
        this.locationUid = locationUid;
    }

    public OrganisationPK getOrganisation() {
        return organisation;
    }

    public void setOrganisation(OrganisationPK organisation) {
        this.organisation = organisation;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((locationUid == null) ? 0 : locationUid.hashCode());
        result = prime * result + ((organisation == null) ? 0 : organisation.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        OmLocationHierarchyPK other = (OmLocationHierarchyPK) obj;
        if (locationUid == null) {
            if (other.locationUid != null)
                return false;
        } else if (!locationUid.equals(other.locationUid))
            return false;
        if (organisation == null) {
            if (other.organisation != null)
                return false;
        } else if (!organisation.equals(other.organisation))
            return false;
        return true;
    }

    private static String encode(String str) {
        return BaseEncoding.base32().encode(str.getBytes(Charset.forName("UTF-8")));
    }

    private static String decode(String str) {
        return new String(BaseEncoding.base32().decode(str), Charset.forName("UTF-8"));
    }

}
