package com.wipro.wess.ods.sourceenergyident;

// Generated Jan 7, 2014 12:15:31 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.jdo.InstanceCallbacks;
import javax.jdo.annotations.Column;
import javax.jdo.annotations.IdGeneratorStrategy;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.Persistent;
import javax.jdo.annotations.Sequence;
import javax.jdo.annotations.SequenceStrategy;

import org.apache.isis.applib.DomainObjectContainer;
import org.apache.isis.applib.annotation.Audited;
import org.apache.isis.applib.annotation.Bookmarkable;
import org.apache.isis.applib.annotation.Hidden;
import org.apache.isis.applib.annotation.ObjectType;
import org.apache.isis.applib.annotation.Where;

/**
 * MSourcecatConfig generated by hbm2java
 */
@javax.jdo.annotations.PersistenceCapable(schema = "gemsods", table = "m_sourcecat_config", identityType = IdentityType.APPLICATION)
// @javax.jdo.annotations.Version(strategy = VersionStrategy.VERSION_NUMBER,
// column = "version")
@javax.jdo.annotations.Queries({ @javax.jdo.annotations.Query(name = "fetch_MSourcecatConfig_by_pk", language = "JDOQL", value = "SELECT "
        + " MSourcecatConfig FROM com.wipro.wess.ods.sourceenergyident.MSourcecatConfig MSourcecatConfig "
        + " WHERE categoryCode == :categoryTypeCode") })
@Audited
@ObjectType("MSourcecatConfig")
@Bookmarkable
@Sequence(name = "sourcecat_id", datastoreSequence = "sourcecat_id", strategy = SequenceStrategy.CONTIGUOUS)
public class MSourcecatConfig implements java.io.Serializable, InstanceCallbacks {

    /**
     * 
     */
    private static final long serialVersionUID = 6321806278527431066L;

    private int sourcecategoryId;

    private String categoryCode;

    private String displayName;

    private String description;

    private String insertedBy;

    private Date insertedTimeTs;

    private Long sourceId;

    private String configUser;

    // private Set<OmSourceidentity> omSourceidentities = new HashSet<OmSourceidentity>(0);

    public MSourcecatConfig() {
    }

    public MSourcecatConfig(int sourcecategoryId, String categoryCode, String displayName, String insertedBy,
            Date insertedTimeTs) {
        this.sourcecategoryId = sourcecategoryId;
        this.categoryCode = categoryCode;
        this.displayName = displayName;
        this.insertedBy = insertedBy;
        this.insertedTimeTs = insertedTimeTs;
    }

    public MSourcecatConfig(int sourcecategoryId, String categoryCode, String displayName, String description,
            String insertedBy, Date insertedTimeTs, Long sourceId/* , Set<OmSourceidentity> omSourceidentities */) {
        this.sourcecategoryId = sourcecategoryId;
        this.categoryCode = categoryCode;
        this.displayName = displayName;
        this.description = description;
        this.insertedBy = insertedBy;
        this.insertedTimeTs = insertedTimeTs;
        this.sourceId = sourceId;
        // this.omSourceidentities = omSourceidentities;
    }

    @Column(allowsNull = "false", name = "sourcecategory_id")
    @Persistent(primaryKey = "true", valueStrategy = IdGeneratorStrategy.SEQUENCE, sequence = "sourcecat_id")
    public int getSourcecategoryId() {
        return this.sourcecategoryId;
    }

    public void setSourcecategoryId(int sourcecategoryId) {
        this.sourcecategoryId = sourcecategoryId;
    }

    @Column(allowsNull = "false", name = "category_code")
    public String getCategoryCode() {
        return this.categoryCode;
    }

    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }

    @Column(allowsNull = "false", name = "display_name")
    public String getDisplayName() {
        return this.displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(allowsNull = "false", name = "inserted_by")
    public String getInsertedBy() {
        return this.insertedBy;
    }

    public void setInsertedBy(String insertedBy) {
        this.insertedBy = insertedBy;
    }

    @Column(allowsNull = "false", name = "inserted_time_ts")
    public Date getInsertedTimeTs() {
        return this.insertedTimeTs;
    }

    public void setInsertedTimeTs(Date insertedTimeTs) {
        this.insertedTimeTs = insertedTimeTs;
    }

    @Column(name = "source_id_")
    public Long getSourceId() {
        return this.sourceId;
    }

    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    @Column(name = "config_user")
    @Hidden(where = Where.EVERYWHERE)
    public String getConfigUser() {
        return configUser;
    }

    public void setConfigUser(String configUser) {
        this.configUser = configUser;
    }

    private DomainObjectContainer container;

    public void injectDomainObjectContainer(final DomainObjectContainer container) {
        this.container = container;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + sourcecategoryId;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        MSourcecatConfig other = (MSourcecatConfig) obj;
        if (sourcecategoryId != other.sourcecategoryId)
            return false;
        return true;
    }

    /*
     * public Set<OmSourceidentity> getOmSourceidentities() { return this.omSourceidentities; } public void
     * setOmSourceidentities(Set<OmSourceidentity> omSourceidentities) { this.omSourceidentities = omSourceidentities; }
     */

    public void jdoPostLoad() {
    }

    public void jdoPreClear() {
    }

    public void jdoPreStore() {
        this.setConfigUser(this.container.getUser().getName());
    }

    public void jdoPreDelete() {
    }

}
