package com.wipro.wess.ods.asset;

import java.nio.charset.Charset;
import java.util.StringTokenizer;

import com.google.common.io.BaseEncoding;
import com.wipro.wess.ods.site.OmSitePK;

// Generated Jan 7, 2014 12:15:31 PM by Hibernate Tools 3.2.2.GA

/**
 * OmAssetExtendedAttrId generated by hbm2java
 */
public class AssetExtendedAttrPK implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -721612605570900600L;

    

    public OmAssetPK assetId;
    
    public OmSitePK site;    

    public String paramName;

    public AssetExtendedAttrPK() {
    }

    public AssetExtendedAttrPK(String key) {
        StringTokenizer token = new StringTokenizer(decode(key), "-");
        this.assetId = new OmAssetPK(token.nextToken());
        this.site = new OmSitePK(token.nextToken());
        this.paramName = token.nextToken();
    }

    
    public OmAssetPK getAssetId() {
        return assetId;
    }

    
    public void setAssetId(OmAssetPK assetId) {
        this.assetId = assetId;
    }

    
    public OmSitePK getSite() {
        return site;
    }

    
    public void setSite(OmSitePK site) {
        this.site = site;
    }

    
    public String getParamName() {
        return paramName;
    }

    
    public void setParamName(String paramName) {
        this.paramName = paramName;
    }
    

    @Override
    public String toString() {
        return encode(this.assetId.toString() + "-" + this.site.toString() + "-" + this.paramName);
    }

    
    
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((assetId == null) ? 0 : assetId.hashCode());
        result = prime * result + ((paramName == null) ? 0 : paramName.hashCode());
        result = prime * result + ((site == null) ? 0 : site.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        AssetExtendedAttrPK other = (AssetExtendedAttrPK) obj;
        if (assetId == null) {
            if (other.assetId != null)
                return false;
        } else if (!assetId.equals(other.assetId))
            return false;
        if (paramName == null) {
            if (other.paramName != null)
                return false;
        } else if (!paramName.equals(other.paramName))
            return false;
        if (site == null) {
            if (other.site != null)
                return false;
        } else if (!site.equals(other.site))
            return false;
        return true;
    }

    private static String encode(String str) {
        return BaseEncoding.base32().encode(str.getBytes(Charset.forName("UTF-8")));
    }

    private static String decode(String str) {
        return new String(BaseEncoding.base32().decode(str), Charset.forName("UTF-8"));
    }

   

}
