package com.wipro.wess.ods.asset;

import java.nio.charset.Charset;
import java.util.StringTokenizer;

import com.google.common.io.BaseEncoding;

// Generated Jan 7, 2014 12:15:31 PM by Hibernate Tools 3.2.2.GA

/**
 * OmAssetspecId generated by hbm2java
 */
public class OmAssetspecPK implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 8201444217978012548L;

    public OmAssetPK assetUid;

    //public OrganisationPK orgId;

    public int attributeId;

    public OmAssetspecPK() {
    }

    public OmAssetspecPK(OmAssetPK assetUid, /*OrganisationPK orgId,*/ int attributeId) {
        this.assetUid = assetUid;
        //this.orgId = orgId;
        this.attributeId = attributeId;
    }
    
    public OmAssetspecPK(String key){
        StringTokenizer token = new StringTokenizer(decode(key), "-");
        this.assetUid = new OmAssetPK(token.nextToken());
       // this.orgId = new OrganisationPK(token.nextToken());
        this.attributeId = Integer.parseInt(token.nextToken());
    }
    
    @Override
    public String toString() {
        return encode(this.assetUid.toString() + "-" /*+ this.orgId.toString()*/ + "-" +this.attributeId);
    }

    public OmAssetPK getAssetUid() {
        return this.assetUid;
    }

    public void setAssetUid(OmAssetPK assetUid) {
        this.assetUid = assetUid;
    }

 /*   public OrganisationPK getOrgId() {
        return this.orgId;
    }

    public void setOrgId(OrganisationPK orgId) {
        this.orgId = orgId;
    }*/

    public int getAttributeId() {
        return this.attributeId;
    }

    public void setAttributeId(int attributeId) {
        this.attributeId = attributeId;
    }

    private static String encode(String str) {
        return BaseEncoding.base32().encode(str.getBytes(Charset.forName("UTF-8")));
    }

    private static String decode(String str) {
        return new String(BaseEncoding.base32().decode(str), Charset.forName("UTF-8"));
    }
    
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((assetUid == null) ? 0 : assetUid.hashCode());
        result = prime * result + attributeId;
        //result = prime * result + ((orgId == null) ? 0 : orgId.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        OmAssetspecPK other = (OmAssetspecPK) obj;
        if (assetUid == null) {
            if (other.assetUid != null)
                return false;
        } else if (!assetUid.equals(other.assetUid))
            return false;
        if (attributeId != other.attributeId)
            return false;
        /*if (orgId == null) {
            if (other.orgId != null)
                return false;
        } else if (!orgId.equals(other.orgId))
            return false;*/
        return true;
    }

}
