package com.wipro.wess.ods.asset;

// Generated Jan 7, 2014 12:15:31 PM by Hibernate Tools 3.2.2.GA

import java.nio.charset.Charset;
import java.util.Date;
import java.util.StringTokenizer;

import com.google.common.io.BaseEncoding;
import com.wipro.wess.ods.utils.DateUtil;

/**
 * OmAssetInfoElementId generated by hbm2java
 */
public class OmAssetInfoElementPK implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 6581755515590728651L;

    public OmAssetPK asset;

    public String measurementEntityId;

    public String measureId;

    public Date startDate;

    public String valueType;

    public OmAssetInfoElementPK() {
    }

    public OmAssetInfoElementPK(OmAssetPK asset, String measurementEntityId, String measureId, Date startDate,
            String valueType) {
        this.asset = asset;
        this.measurementEntityId = measurementEntityId;
        this.measureId = measureId;
        this.startDate = startDate;
        this.valueType = valueType;
    }

    public OmAssetInfoElementPK(String key) {
        StringTokenizer token = new StringTokenizer(decode(key), "~");
        this.asset = new OmAssetPK(token.nextToken());
        this.measurementEntityId = token.nextToken();
        this.measureId = token.nextToken();
        this.startDate = DateUtil.parse(token.nextToken(), null);
        this.valueType = token.nextToken();
    }

    @Override
    public String toString() {
        return encode("" + this.asset.toString() + "~" + this.measurementEntityId + "~" + this.measureId + "~"
                + DateUtil.format(this.startDate, null) + "~" + this.valueType);
    }

    public OmAssetPK getAsset() {
        return asset;
    }

    public void setAsset(OmAssetPK asset) {
        this.asset = asset;
    }

    public String getMeasurementEntityId() {
        return this.measurementEntityId;
    }

    public void setMeasurementEntityId(String measurementEntityId) {
        this.measurementEntityId = measurementEntityId;
    }

    public String getMeasureId() {
        return this.measureId;
    }

    public void setMeasureId(String measureId) {
        this.measureId = measureId;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public String getValueType() {
        return this.valueType;
    }

    public void setValueType(String valueType) {
        this.valueType = valueType;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((asset == null) ? 0 : asset.hashCode());
        result = prime * result + ((measureId == null) ? 0 : measureId.hashCode());
        result = prime * result + ((measurementEntityId == null) ? 0 : measurementEntityId.hashCode());
        result = prime * result + ((startDate == null) ? 0 : startDate.hashCode());
        result = prime * result + ((valueType == null) ? 0 : valueType.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        OmAssetInfoElementPK other = (OmAssetInfoElementPK) obj;
        if (asset == null) {
            if (other.asset != null)
                return false;
        } else if (!asset.equals(other.asset))
            return false;
        if (measureId == null) {
            if (other.measureId != null)
                return false;
        } else if (!measureId.equals(other.measureId))
            return false;
        if (measurementEntityId == null) {
            if (other.measurementEntityId != null)
                return false;
        } else if (!measurementEntityId.equals(other.measurementEntityId))
            return false;
        if (startDate == null) {
            if (other.startDate != null)
                return false;
        } else if (!startDate.equals(other.startDate))
            return false;
        if (valueType == null) {
            if (other.valueType != null)
                return false;
        } else if (!valueType.equals(other.valueType))
            return false;
        return true;
    }

    private static String encode(String str) {

        return BaseEncoding.base32().encode(str.getBytes(Charset.forName("UTF-8")));
    }

    private static String decode(String str) {
        return new String(BaseEncoding.base32().decode(str), Charset.forName("UTF-8"));
    }

}
