package com.wipro.wess.ods.service;

// Generated Jan 7, 2014 12:15:31 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.jdo.InstanceCallbacks;
import javax.jdo.annotations.Column;
import javax.jdo.annotations.Columns;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.Persistent;

import org.apache.isis.applib.DomainObjectContainer;
import org.apache.isis.applib.annotation.Audited;
import org.apache.isis.applib.annotation.Bookmarkable;
import org.apache.isis.applib.annotation.Bulk;
import org.apache.isis.applib.annotation.CssClass;
import org.apache.isis.applib.annotation.Hidden;
import org.apache.isis.applib.annotation.Named;
import org.apache.isis.applib.annotation.ObjectType;
import org.apache.isis.applib.annotation.Optional;
import org.apache.isis.applib.annotation.Title;
import org.apache.isis.applib.annotation.Where;

import com.wipro.wess.ods.site.OmSite;
import com.wipro.wess.ods.site.OmSiteService;

/**
 * OmServiceConfig generated by hbm2java
 */
@Named("ServiceConfig")
@Bookmarkable
@Audited
@ObjectType("OmServiceConfig")
@javax.jdo.annotations.PersistenceCapable(schema = "gemsods", table = "om_service_config", objectIdClass = ServiceConfigPK.class, identityType = IdentityType.APPLICATION)
@javax.jdo.annotations.Queries({
        @javax.jdo.annotations.Query(name = "fetch_om_service_config_by_pk", language = "JDOQL", value = "SELECT "
                + " OmServiceConfig FROM com.wipro.wess.ods.service.OmServiceConfig OmServiceConfig WHERE serviceUid == :serviceUid"),
        @javax.jdo.annotations.Query(name = "fetch_om_service_config_by_service_type", language = "JDOQL", value = "SELECT "
                + " OmServiceConfig FROM com.wipro.wess.ods.service.OmServiceConfig OmServiceConfig WHERE serviceType == :serviceType"),
        @javax.jdo.annotations.Query(name = "fetch_serviceconfigs_by_user", language = "JPQL", value = "SELECT service FROM com.wipro.wess.ods.service.OmServiceConfig service "
                + " JOIN service.site site WHERE EXISTS "
                + " (SELECT 1 FROM com.wipro.wess.pdm.security.OmPermission permission WHERE permission.site = site AND permission IN "
                + " (SELECT "
                + " OmRolesPermissions.permission FROM com.wipro.wess.pdm.security.OmRolesPermissions OmRolesPermissions "
                + " WHERE role IN ( SELECT OmUsersRoles.role FROM com.wipro.wess.pdm.security.OmUsersRoles OmUsersRoles WHERE OmUsersRoles.user.userName = :userName) ) ) ") })
public class OmServiceConfig implements java.io.Serializable, InstanceCallbacks {

    /**
     * 
     */
    private static final long serialVersionUID = -8687161106178930316L;

    private String serviceUid;

    // private MOrganisation MOrganisation;

    private OmSite site;

    private String description;

    private String serviceType;

    private BigDecimal energyCostPerUnit;

    private String status;

    private String isByproduct;

    private String serviceEffFormula;

    private String serviceQaFormula;

    private String serviceQtyFormula;

    private String subtypeLvl2;

    private String changeBy;

    private Date changeTs;

    private String configUser;

    /*
     * private Set<OmScaServiceMap> omScaServiceMaps = new HashSet<OmScaServiceMap>(0); private
     * Set<OmSupplierAssetServiceMap> omSupplierAssetServiceMaps = new HashSet<OmSupplierAssetServiceMap>(0);
     */

    private OmSiteService siteService;

    public void injectOmSiteService(OmSiteService siteService) {
        this.siteService = siteService;
    }

    public List<OmSite> choicesSite() {
        return this.siteService.listAllSites();
    }

    public OmServiceConfig() {
    }

    public OmServiceConfig(String serviceUid, String changeBy, Date changeTs) {
        this.serviceUid = serviceUid;
        this.changeBy = changeBy;
        this.changeTs = changeTs;
    }

    public OmServiceConfig(String serviceUid, /* MOrganisation MOrganisation, */String description, String serviceType,
            BigDecimal energyCostPerUnit, String status, String isByproduct, String serviceEffFormula,
            String serviceQaFormula, String serviceQtyFormula, String subtypeLvl2, String changeBy, Date changeTs/*
                                                                                                                  * ,
                                                                                                                  * Set<
                                                                                                                  * OmScaServiceMap
                                                                                                                  * >
                                                                                                                  * omScaServiceMaps
                                                                                                                  */) {
        this.serviceUid = serviceUid;
        // this.MOrganisation = MOrganisation;
        this.description = description;
        this.serviceType = serviceType;
        this.energyCostPerUnit = energyCostPerUnit;
        this.status = status;
        this.isByproduct = isByproduct;
        this.serviceEffFormula = serviceEffFormula;
        this.serviceQaFormula = serviceQaFormula;
        this.serviceQtyFormula = serviceQtyFormula;
        this.subtypeLvl2 = subtypeLvl2;
        this.changeBy = changeBy;
        this.changeTs = changeTs;
        // this.omScaServiceMaps = omScaServiceMaps;
    }

    @Column(allowsNull = "false", name = "service_uid")
    @Title
    @Persistent(primaryKey = "true")
    public String getServiceUid() {
        return this.serviceUid;
    }

    public void setServiceUid(String serviceUid) {
        this.serviceUid = serviceUid;
    }

    /*
     * @Column(allowsNull = "false", name = "org_id") public MOrganisation getMOrganisation() { return
     * this.MOrganisation; } public void setMOrganisation(MOrganisation MOrganisation) { this.MOrganisation =
     * MOrganisation; }
     */

    @Columns(value = { @Column(name = "org_id"), @Column(name = "site_id") })
    @Optional
    public OmSite getSite() {
        return site;
    }

    public void setSite(OmSite site) {
        this.site = site;
    }

    @Column(name = "description")
    @Hidden(where = Where.ALL_TABLES)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "service_type")
    @Hidden(where = Where.ALL_TABLES)
    public String getServiceType() {
        return this.serviceType;
    }

    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    @Column(name = "energy_cost_per_unit")
    @Hidden(where = Where.ALL_TABLES)
    public BigDecimal getEnergyCostPerUnit() {
        return this.energyCostPerUnit;
    }

    public void setEnergyCostPerUnit(BigDecimal energyCostPerUnit) {
        this.energyCostPerUnit = energyCostPerUnit;
    }

    @Column(name = "status")
    @Hidden(where = Where.ALL_TABLES)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "is_byproduct")
    @Hidden(where = Where.ALL_TABLES)
    public String getIsByproduct() {
        return this.isByproduct;
    }

    public void setIsByproduct(String isByproduct) {
        this.isByproduct = isByproduct;
    }

    @Column(name = "service_eff_formula")
    @Hidden(where = Where.ALL_TABLES)
    public String getServiceEffFormula() {
        return this.serviceEffFormula;
    }

    public void setServiceEffFormula(String serviceEffFormula) {
        this.serviceEffFormula = serviceEffFormula;
    }

    @Column(name = "service_qa_formula")
    @Hidden(where = Where.ALL_TABLES)
    public String getServiceQaFormula() {
        return this.serviceQaFormula;
    }

    public void setServiceQaFormula(String serviceQaFormula) {
        this.serviceQaFormula = serviceQaFormula;
    }

    @Column(name = "service_qty_formula")
    @Hidden(where = Where.ALL_TABLES)
    public String getServiceQtyFormula() {
        return this.serviceQtyFormula;
    }

    public void setServiceQtyFormula(String serviceQtyFormula) {
        this.serviceQtyFormula = serviceQtyFormula;
    }

    @Column(name = "subtype_lvl2")
    @Hidden(where = Where.ALL_TABLES)
    public String getSubtypeLvl2() {
        return this.subtypeLvl2;
    }

    public void setSubtypeLvl2(String subtypeLvl2) {
        this.subtypeLvl2 = subtypeLvl2;
    }

    @Column(name = "change_by")
    @Hidden(where = Where.OBJECT_FORMS)
    public String getChangeBy() {
        return this.changeBy;
    }

    public void setChangeBy(String changeBy) {
        this.changeBy = changeBy;
    }

    @Column(name = "change_ts")
    @Hidden(where = Where.OBJECT_FORMS)
    public Date getChangeTs() {
        return this.changeTs;
    }

    public void setChangeTs(Date changeTs) {
        this.changeTs = changeTs;
    }

    /*
     * public Set<OmScaServiceMap> getOmScaServiceMaps() { return this.omScaServiceMaps; } public void
     * setOmScaServiceMaps(Set<OmScaServiceMap> omScaServiceMaps) { this.omScaServiceMaps = omScaServiceMaps; }
     * @Persistent(mappedBy = "omServiceConfig", dependentElement = "true") public Set<OmSupplierAssetServiceMap>
     * getOmSupplierAssetServiceMaps() { return omSupplierAssetServiceMaps; } public void
     * setOmSupplierAssetServiceMaps(Set<OmSupplierAssetServiceMap> omSupplierAssetServiceMaps) {
     * this.omSupplierAssetServiceMaps = omSupplierAssetServiceMaps; }
     */

    @Column(name = "config_user")
    @Hidden(where = Where.EVERYWHERE)
    public String getConfigUser() {
        return configUser;
    }

    public void setConfigUser(String configUser) {
        this.configUser = configUser;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((serviceUid == null) ? 0 : serviceUid.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        OmServiceConfig other = (OmServiceConfig) obj;
        if (serviceUid == null) {
            if (other.serviceUid != null)
                return false;
        } else if (!serviceUid.equals(other.serviceUid))
            return false;
        return true;
    }

    private DomainObjectContainer container;

    public void injectDomainObjectContainer(final DomainObjectContainer container) {
        this.container = container;
    }

    public void jdoPostLoad() {
    }

    public void jdoPreClear() {
    }

    public void jdoPreStore() {
        this.setChangeBy(this.container.getUser().getName());
        this.setChangeTs(new Date());
        this.setConfigUser(this.container.getUser().getName());
    }

    public void jdoPreDelete() {
    }

    private OmServiceConfigService serviceConfigService;

    public void injectOmServiceConfigService(OmServiceConfigService serviceConfigService) {
        this.serviceConfigService = serviceConfigService;
    }

    @Bulk
    @CssClass("x-caution")
    public List<OmServiceConfig> delete() {
        this.container.removeIfNotAlready(this);
        this.container.informUser("Deleted " + container.titleOf(this));
        return this.serviceConfigService.listAllServiceConfigs();

    }

}
