package com.wipro.wess.ods.sca;

import java.nio.charset.Charset;
import java.util.StringTokenizer;

import com.google.common.io.BaseEncoding;
import com.wipro.wess.ods.asset.OmAssetPK;

// Generated Jan 7, 2014 12:15:31 PM by Hibernate Tools 3.2.2.GA

/**
 * OmScaMonitorassetMapId generated by hbm2java
 */
public class OmScaMonitorassetMapPK implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -8647835002030058734L;

    public ScaConfigPK scaUid;

    public OmAssetPK monitorAssetUid;

    public OmScaMonitorassetMapPK() {
    }

    public OmScaMonitorassetMapPK(ScaConfigPK scaUid, OmAssetPK monitorAssetUid) {
        this.scaUid = scaUid;
        this.monitorAssetUid = monitorAssetUid;
    }
    
    public OmScaMonitorassetMapPK(String key){
        StringTokenizer token = new StringTokenizer(decode(key), "-");
        this.scaUid = new ScaConfigPK(token.nextToken());
        this.monitorAssetUid = new OmAssetPK(token.nextToken());
    }
    
    @Override
    public String toString() {
        return encode(this.scaUid.toString() + "-" + this.monitorAssetUid.toString());
    }

    public ScaConfigPK getScaUid() {
        return this.scaUid;
    }

    public void setScaUid(ScaConfigPK scaUid) {
        this.scaUid = scaUid;
    }

    public OmAssetPK getMonitorAssetUid() {
        return this.monitorAssetUid;
    }

    public void setMonitorAssetUid(OmAssetPK monitorAssetUid) {
        this.monitorAssetUid = monitorAssetUid;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((monitorAssetUid == null) ? 0 : monitorAssetUid.hashCode());
        result = prime * result + ((scaUid == null) ? 0 : scaUid.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        OmScaMonitorassetMapPK other = (OmScaMonitorassetMapPK) obj;
        if (monitorAssetUid == null) {
            if (other.monitorAssetUid != null)
                return false;
        } else if (!monitorAssetUid.equals(other.monitorAssetUid))
            return false;
        if (scaUid == null) {
            if (other.scaUid != null)
                return false;
        } else if (!scaUid.equals(other.scaUid))
            return false;
        return true;
    }

    private static String encode(String str) {
        return BaseEncoding.base32().encode(str.getBytes(Charset.forName("UTF-8")));
    }

    private static String decode(String str) {
        return new String(BaseEncoding.base32().decode(str), Charset.forName("UTF-8"));
    }

}
