package com.wipro.wess.ods.sca;

// Generated Jan 7, 2014 12:15:31 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.List;

import javax.jdo.InstanceCallbacks;
import javax.jdo.annotations.Column;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.Persistent;

import org.apache.isis.applib.DomainObjectContainer;
import org.apache.isis.applib.annotation.Audited;
import org.apache.isis.applib.annotation.Bookmarkable;
import org.apache.isis.applib.annotation.Bulk;
import org.apache.isis.applib.annotation.CssClass;
import org.apache.isis.applib.annotation.Hidden;
import org.apache.isis.applib.annotation.Named;
import org.apache.isis.applib.annotation.ObjectType;
import org.apache.isis.applib.annotation.Title;
import org.apache.isis.applib.annotation.Where;

/**
 * OmScaConfigExtAttr generated by hbm2java
 */
@Named("SCAExtAttr")
@Bookmarkable
@Audited
@ObjectType("OmScaConfigExtAttr")
@javax.jdo.annotations.PersistenceCapable(schema = "gemsods", table = "om_sca_config_ext_attr", objectIdClass = OmScaConfigExtAttrPK.class, identityType = IdentityType.APPLICATION)
@javax.jdo.annotations.Queries({
        @javax.jdo.annotations.Query(name = "fetch_OmScaConfigExtAttr_by_pk", language = "JDOQL", value = "SELECT "
                + " OmScaConfigExtAttr FROM com.wipro.wess.ods.sca.OmScaConfigExtAttr OmScaConfigExtAttr WHERE scaUid == :scaUid && attributeName == :attributeName"),
        @javax.jdo.annotations.Query(name = "fetch_scaextattrs_by_user", language = "JPQL", value = "SELECT scaext FROM com.wipro.wess.ods.sca.OmScaConfigExtAttr scaext "
                + " JOIN scaext.scaUid sca "
                + " JOIN sca.omSite site WHERE EXISTS "
                + " (SELECT 1 FROM com.wipro.wess.pdm.security.OmPermission permission WHERE permission.site = site AND permission IN "
                + " (SELECT "
                + " OmRolesPermissions.permission FROM com.wipro.wess.pdm.security.OmRolesPermissions OmRolesPermissions "
                + " WHERE role IN ( SELECT OmUsersRoles.role FROM com.wipro.wess.pdm.security.OmUsersRoles OmUsersRoles WHERE OmUsersRoles.user.userName = :userName) ) ) ") })
public class OmScaConfigExtAttr implements java.io.Serializable, InstanceCallbacks {

    /**
     * 
     */
    private static final long serialVersionUID = -6659278197507480067L;

    private String attributeName;

    private OmScaConfig scaUid;

    private BigDecimal numValue;

    private String alnValue;

    private String configUser;
    
    public OmScaConfigExtAttr() {
    }

    public OmScaConfigExtAttr(OmScaConfig scaUid, String attributeName) {
        this.scaUid = scaUid;
        this.attributeName = attributeName;
    }

    public OmScaConfigExtAttr(OmScaConfig scaUid, String attributeName, BigDecimal numValue, String alnValue) {
        this.scaUid = scaUid;
        this.attributeName = attributeName;
        this.numValue = numValue;
        this.alnValue = alnValue;
    }

    @Column(allowsNull = "false", name = "attribute_name")
    @Title
    @Persistent(primaryKey = "true")
    public String getAttributeName() {
        return attributeName;
    }

    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }

    @Column(allowsNull = "false", name = "sca_uid")
    @Title
    @Persistent(primaryKey = "true", dependent = "false")
    public OmScaConfig getScaUid() {
        return scaUid;
    }

    public void setScaUid(OmScaConfig scaUid) {
        this.scaUid = scaUid;
    }

    @Column(name = "num_value")
    public BigDecimal getNumValue() {
        return this.numValue;
    }

    public void setNumValue(BigDecimal numValue) {
        this.numValue = numValue;
    }

    @Column(name = "aln_value")
    public String getAlnValue() {
        return this.alnValue;
    }

    public void setAlnValue(String alnValue) {
        this.alnValue = alnValue;
    }


    @Column(name = "config_user")
    @Hidden(where = Where.EVERYWHERE)
    public String getConfigUser() {
        return configUser;
    }

    public void setConfigUser(String configUser) {
        this.configUser = configUser;
    }
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((attributeName == null) ? 0 : attributeName.hashCode());
        result = prime * result + ((scaUid == null) ? 0 : scaUid.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        OmScaConfigExtAttr other = (OmScaConfigExtAttr) obj;
        if (attributeName == null) {
            if (other.attributeName != null)
                return false;
        } else if (!attributeName.equals(other.attributeName))
            return false;
        if (scaUid == null) {
            if (other.scaUid != null)
                return false;
        } else if (!scaUid.equals(other.scaUid))
            return false;
        return true;
    }
    
    private DomainObjectContainer container;

    public void injectDomainObjectContainer(final DomainObjectContainer container) {
        this.container = container;
    }

    public void jdoPostLoad() {
    }

    public void jdoPreClear() {
    }

    public void jdoPreStore() {
        this.setConfigUser(this.container.getUser().getName());
    }

    public void jdoPreDelete() {
    }

    private OmScaConfigService scaConfigService;

    public void injectOmScaConfigService(OmScaConfigService scaConfigService) {
        this.scaConfigService = scaConfigService;
    }

    @Bulk
    @CssClass("x-caution")
    public List<OmScaConfigExtAttr> delete() {
        this.container.removeIfNotAlready(this);
        this.container.informUser("Deleted " + container.titleOf(this));
        return this.scaConfigService.listAllScaConfigExtAttrs();

    }
}
