package com.wipro.wess.ods.msa;

import java.nio.charset.Charset;
import java.util.StringTokenizer;

import com.google.common.io.BaseEncoding;
import com.wipro.wess.ods.organisation.OrganisationPK;

// Generated Jan 7, 2014 12:15:31 PM by Hibernate Tools 3.2.2.GA

/**
 * OmModeOfOperationConfigId generated by hbm2java
 */
public class OmModeOfOperationConfigPK implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 6056152139767513281L;

    public OrganisationPK organisation;

    public String modeName;

    public OmModeOfOperationConfigPK() {
    }

    public OmModeOfOperationConfigPK(String key) {
        StringTokenizer token = new StringTokenizer(decode(key), "-");
        this.modeName = token.nextToken();
        this.organisation = new OrganisationPK(token.nextToken());
    }

    public OrganisationPK getOrganisation() {
        return organisation;
    }

    public void setOrganisation(OrganisationPK organisation) {
        this.organisation = organisation;
    }

    public String getModeName() {
        return this.modeName;
    }

    public void setModeName(String modeName) {
        this.modeName = modeName;
    }
    
    

    @Override
    public String toString() {
        return encode(this.modeName + "-" + this.organisation.toString());
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((modeName == null) ? 0 : modeName.hashCode());
        result = prime * result + ((organisation == null) ? 0 : organisation.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        OmModeOfOperationConfigPK other = (OmModeOfOperationConfigPK) obj;
        if (modeName == null) {
            if (other.modeName != null)
                return false;
        } else if (!modeName.equals(other.modeName))
            return false;
        if (organisation == null) {
            if (other.organisation != null)
                return false;
        } else if (!organisation.equals(other.organisation))
            return false;
        return true;
    }

    private static String encode(String str) {
        return BaseEncoding.base32().encode(str.getBytes(Charset.forName("UTF-8")));
    }

    private static String decode(String str) {
        return new String(BaseEncoding.base32().decode(str), Charset.forName("UTF-8"));
    }

}
