package com.wipro.wess.ods.msa;

// Generated Jan 7, 2014 12:15:31 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.List;

import javax.jdo.InstanceCallbacks;
import javax.jdo.annotations.Column;
import javax.jdo.annotations.IdGeneratorStrategy;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.Persistent;

import org.apache.isis.applib.DomainObjectContainer;
import org.apache.isis.applib.annotation.Audited;
import org.apache.isis.applib.annotation.Bookmarkable;
import org.apache.isis.applib.annotation.Bulk;
import org.apache.isis.applib.annotation.CssClass;
import org.apache.isis.applib.annotation.Hidden;
import org.apache.isis.applib.annotation.Named;
import org.apache.isis.applib.annotation.ObjectType;
import org.apache.isis.applib.annotation.Title;
import org.apache.isis.applib.annotation.Where;

import com.wipro.wess.ods.organisation.MOrganisation;
import com.wipro.wess.ods.sca.OmScaConfig;
import com.wipro.wess.ods.sca.OmScaConfigService;

/**
 * OmMsaScaMap generated by hbm2java
 */
@Named("MsaScaMap")
@Bookmarkable
@Audited
@ObjectType("OmMsaScaMap")
@javax.jdo.annotations.PersistenceCapable(schema = "gemsods", table = "om_msa_sca_map", objectIdClass = OmMsaScaMapPK.class, identityType = IdentityType.APPLICATION)
@javax.jdo.annotations.Queries({
        @javax.jdo.annotations.Query(name = "fetch_OmMsaScaMap_by_msa_sca_map", language = "JDOQL", value = "SELECT "
                + " OmMsaScaMap FROM com.wipro.wess.ods.msa.OmMsaScaMap OmMsaScaMap WHERE omScaConfig == :omScaConfig && omMsaConfig == :omMsaConfig "),
        @javax.jdo.annotations.Query(name = "fetch_OmMsaScaMap_by_pk", language = "JDOQL", value = "SELECT "
                + " OmMsaScaMap FROM com.wipro.wess.ods.msa.OmMsaScaMap OmMsaScaMap WHERE msaScaMapId == :msaScaMapId "),
        @javax.jdo.annotations.Query(name = "fetch_msascamap_by_user", language = "JPQL", value = "SELECT msasca FROM com.wipro.wess.ods.msa.OmMsaScaMap msasca "
                + " WHERE msasca.omMsaConfig IN ("
                + " SELECT msasitemap.msaUid FROM com.wipro.wess.ods.site.OmMsaSiteMap msasitemap"
                + " JOIN msasitemap.omSite site WHERE EXISTS "
                + " (SELECT 1 FROM com.wipro.wess.pdm.security.OmPermission permission WHERE permission.site = site AND permission IN "
                + " (SELECT "
                + " OmRolesPermissions.permission FROM com.wipro.wess.pdm.security.OmRolesPermissions OmRolesPermissions "
                + " WHERE role IN ( SELECT OmUsersRoles.role FROM com.wipro.wess.pdm.security.OmUsersRoles OmUsersRoles WHERE OmUsersRoles.user.userName = :userName) ) ) ) ") })
public class OmMsaScaMap implements java.io.Serializable, InstanceCallbacks {

    /**
     * 
     */
    private static final long serialVersionUID = -6592770967654695208L;

    private long msaScaMapId;

    private OmScaConfig omScaConfig;

    private OmMsaConfig omMsaConfig;

    private MOrganisation orgId;

    private String changeBy;

    private Date changeDt;
    
    private String configUser;

    public OmMsaScaMap() {
    }

    public OmMsaScaMap(long msaScaMapId, OmScaConfig omScaConfig, OmMsaConfig omMsaConfig, String changeBy,
            Date changeDt) {
        this.msaScaMapId = msaScaMapId;
        this.omScaConfig = omScaConfig;
        this.omMsaConfig = omMsaConfig;
        this.changeBy = changeBy;
        this.changeDt = changeDt;
    }

    @Column(allowsNull = "false", name = "msa_sca_map_id")
    @Title
    @Persistent(primaryKey = "true", valueStrategy = IdGeneratorStrategy.INCREMENT)
    @Hidden(where = Where.ANYWHERE)
    public long getMsaScaMapId() {
        return this.msaScaMapId;
    }

    public void setMsaScaMapId(long msaScaMapId) {
        this.msaScaMapId = msaScaMapId;
    }

    @Column(allowsNull = "false", name = "sca_uid")
    public OmScaConfig getOmScaConfig() {
        return this.omScaConfig;
    }

    public void setOmScaConfig(OmScaConfig omScaConfig) {
        this.omScaConfig = omScaConfig;
    }

    @Column(allowsNull = "false", name = "msa_uid")
    public OmMsaConfig getOmMsaConfig() {
        return this.omMsaConfig;
    }

    public void setOmMsaConfig(OmMsaConfig omMsaConfig) {
        this.omMsaConfig = omMsaConfig;
    }

    @Column(allowsNull = "false", name = "org_id")
    @Hidden(where = Where.ANYWHERE)
    public MOrganisation getOrgId() {
        return orgId;
    }

    public void setOrgId(MOrganisation orgId) {
        this.orgId = orgId;
    }

    @Column(allowsNull = "false", name = "change_by")
    @Hidden(where = Where.OBJECT_FORMS)
    public String getChangeBy() {
        return this.changeBy;
    }

    public void setChangeBy(String changeBy) {
        this.changeBy = changeBy;
    }

    @Column(allowsNull = "false", name = "change_dt")
    @Hidden(where = Where.OBJECT_FORMS)
    public Date getChangeDt() {
        return this.changeDt;
    }

    public void setChangeDt(Date changeDt) {
        this.changeDt = changeDt;
    }

    @Column(name = "config_user")
    @Hidden(where = Where.EVERYWHERE)
    public String getConfigUser() {
        return configUser;
    }

    public void setConfigUser(String configUser) {
        this.configUser = configUser;
    }
    
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + (int) (msaScaMapId ^ (msaScaMapId >>> 32));
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        OmMsaScaMap other = (OmMsaScaMap) obj;
        if (msaScaMapId != other.msaScaMapId)
            return false;
        return true;
    }

    private OmScaConfigService scaService;

    private OmMsaConfigService msaConfigService;

    public void injectOmScaConfigService(OmScaConfigService scaService) {
        this.scaService = scaService;
    }

    public void injectOmMsaConfigService(OmMsaConfigService msaConfigService) {
        this.msaConfigService = msaConfigService;
    }

    public List<OmMsaConfig> choicesOmMsaConfig() {
        return this.msaConfigService.listAllMsaConfigs();
    }

    public List<OmScaConfig> choicesOmScaConfig() {
        return this.scaService.listAllScaConfigs();
    }

    private DomainObjectContainer container;

    public void injectDomainObjectContainer(final DomainObjectContainer container) {
        this.container = container;
    }

    public void jdoPostLoad() {
    }

    public void jdoPreClear() {
    }

    public void jdoPreStore() {
        this.setChangeBy(this.container.getUser().getName());
        this.setChangeDt(new Date());
        this.setConfigUser(this.container.getUser().getName());
    }

    public void jdoPreDelete() {
    }
    


    @Bulk
    @CssClass("x-caution")
    public List<OmMsaScaMap> delete() {
        this.container.removeIfNotAlready(this);
        this.container.informUser("Deleted " + container.titleOf(this));
        return this.msaConfigService.listAllMsaScaMap();

    }
}
