package com.wipro.wess.ods.uom;

// Generated Jan 7, 2014 12:15:31 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.jdo.InstanceCallbacks;
import javax.jdo.annotations.Column;
import javax.jdo.annotations.IdGeneratorStrategy;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.Persistent;

import org.apache.isis.applib.DomainObjectContainer;
import org.apache.isis.applib.annotation.Audited;
import org.apache.isis.applib.annotation.Bookmarkable;
import org.apache.isis.applib.annotation.Hidden;
import org.apache.isis.applib.annotation.ObjectType;
import org.apache.isis.applib.annotation.Title;
import org.apache.isis.applib.annotation.Where;

/**
 * MExtDataSourceInfo generated by hbm2java
 */
@javax.jdo.annotations.PersistenceCapable(schema = "gemsods", table = "m_ext_data_source_info", objectIdClass = MExtDataSourceInfoPK.class, identityType = IdentityType.APPLICATION)
@Audited
@Bookmarkable
@ObjectType("MExtDataSourceInfo")
public class MExtDataSourceInfo implements java.io.Serializable, InstanceCallbacks {

    /**
     * 
     */
    private static final long serialVersionUID = -8415016707160013970L;

    private String extDataSourceId;

    private int recordId;

    private String extDataSourceDesc;

    private Date changeDate;

    private Long sourceId;
    
    private String configUser;

    // private Set<OmUomExtDataSourceExcept> omUomExtDataSourceExcepts = new HashSet<OmUomExtDataSourceExcept>(0);

    public MExtDataSourceInfo() {
    }

    public MExtDataSourceInfo(String extDataSourceId, int recordId, String extDataSourceDesc, Date changeDate) {
        this.extDataSourceId = extDataSourceId;
        this.recordId = recordId;
        this.extDataSourceDesc = extDataSourceDesc;
        this.changeDate = changeDate;
    }

    public MExtDataSourceInfo(String extDataSourceId, int recordId, String extDataSourceDesc, Date changeDate,
            Long sourceId) {
        this.extDataSourceId = extDataSourceId;
        this.recordId = recordId;
        this.extDataSourceDesc = extDataSourceDesc;
        this.changeDate = changeDate;
        this.sourceId = sourceId;
    }

    @Column(name = "ext_data_source_id", allowsNull = "false")
    @Persistent(primaryKey = "true")
    @Title
    public String getExtDataSourceId() {
        return this.extDataSourceId;
    }

    public void setExtDataSourceId(String extDataSourceId) {
        this.extDataSourceId = extDataSourceId;
    }

    @Column(name = "record_id", allowsNull = "false")
    @Persistent(valueStrategy = IdGeneratorStrategy.INCREMENT)
    @Hidden(where = Where.OBJECT_FORMS)
    public int getRecordId() {
        return this.recordId;
    }

    public void setRecordId(int recordId) {
        this.recordId = recordId;
    }

    @Column(name = "ext_data_source_desc", allowsNull = "false")
    public String getExtDataSourceDesc() {
        return this.extDataSourceDesc;
    }

    public void setExtDataSourceDesc(String extDataSourceDesc) {
        this.extDataSourceDesc = extDataSourceDesc;
    }

    @Column(name = "change_date", allowsNull = "false")
    @Hidden(where = Where.OBJECT_FORMS)
    public Date getChangeDate() {
        return this.changeDate;
    }

    public void setChangeDate(Date changeDate) {
        this.changeDate = changeDate;
    }

    @Column(name = "source_id", allowsNull = "false")
    @Hidden(where = Where.ALL_TABLES)
    public Long getSourceId() {
        return this.sourceId;
    }

    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }
    
    @Column(name = "config_user")
    @Hidden(where = Where.EVERYWHERE)
    public String getConfigUser() {
        return configUser;
    }

    public void setConfigUser(String configUser) {
        this.configUser = configUser;
    }
    
    private DomainObjectContainer container;

    public void injectDomainObjectContainer(final DomainObjectContainer container) {
        this.container = container;
    }
    
    public void jdoPostLoad() {
    }

    public void jdoPreClear() {
    }

    public void jdoPreStore() {
        this.setConfigUser(this.container.getUser().getName());
    }

    public void jdoPreDelete() {
    }

}
