package com.wipro.wess.ods.uom;

import java.util.StringTokenizer;

import com.wipro.wess.ods.masterconfig.MPointlistPK;
import com.wipro.wess.ods.organisation.OrganisationPK;
import com.wipro.wess.ods.upload.ProvisioningConstants;
import com.wipro.wess.ods.utils.OmUtil;

// Generated Jan 7, 2014 12:15:31 PM by Hibernate Tools 3.2.2.GA

/**
 * OmPointlistOrgPolicyId generated by hbm2java
 */
public class OmPointlistOrgPolicyPK implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -7711032864356404504L;

    public OrganisationPK orgId;

    public MPointlistPK pointList;

    public OmPointlistOrgPolicyPK() {
    }

    public OmPointlistOrgPolicyPK(OrganisationPK orgId, MPointlistPK pointList) {
        this.orgId = orgId;
        this.pointList = pointList;
    }

    public OmPointlistOrgPolicyPK(String key) {
        StringTokenizer token = new StringTokenizer(OmUtil.decode(key), ProvisioningConstants.DOMAIN_OBJ_SEPERATOR);
        this.orgId = new OrganisationPK(token.nextToken());
        this.pointList = new MPointlistPK(token.nextToken());
    }

    @Override
    public String toString() {
        return OmUtil.encode("" + this.orgId.toString() + ProvisioningConstants.DOMAIN_OBJ_SEPERATOR
                + this.pointList.toString());
    }

    public OrganisationPK getOrgId() {
        return this.orgId;
    }

    public void setOrgId(OrganisationPK orgId) {
        this.orgId = orgId;
    }

    public MPointlistPK getPointList() {
        return pointList;
    }

    public void setPointList(MPointlistPK pointList) {
        this.pointList = pointList;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((orgId == null) ? 0 : orgId.hashCode());
        result = prime * result + ((pointList == null) ? 0 : pointList.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        OmPointlistOrgPolicyPK other = (OmPointlistOrgPolicyPK) obj;
        if (orgId == null) {
            if (other.orgId != null)
                return false;
        } else if (!orgId.equals(other.orgId))
            return false;
        if (pointList == null) {
            if (other.pointList != null)
                return false;
        } else if (!pointList.equals(other.pointList))
            return false;
        return true;
    }

}
