package com.wipro.wess.ods.uom;

// Generated Jan 7, 2014 12:15:31 PM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.jdo.InstanceCallbacks;
import javax.jdo.annotations.Column;
import javax.jdo.annotations.Columns;
import javax.jdo.annotations.IdGeneratorStrategy;
import javax.jdo.annotations.IdentityType;
import javax.jdo.annotations.Persistent;

import org.apache.isis.applib.DomainObjectContainer;
import org.apache.isis.applib.annotation.Audited;
import org.apache.isis.applib.annotation.Bookmarkable;
import org.apache.isis.applib.annotation.Bulk;
import org.apache.isis.applib.annotation.CssClass;
import org.apache.isis.applib.annotation.Hidden;
import org.apache.isis.applib.annotation.Mandatory;
import org.apache.isis.applib.annotation.ObjectType;
import org.apache.isis.applib.annotation.Title;
import org.apache.isis.applib.annotation.Where;

import com.wipro.wess.ods.masterconfig.MPointlist;
import com.wipro.wess.ods.masterconfig.MasterConfigurationService;
import com.wipro.wess.ods.munit.MUnit;
import com.wipro.wess.ods.munit.MUnitFamily;
import com.wipro.wess.ods.organisation.MOrganisation;
import com.wipro.wess.ods.organisation.OrganisationService;

/**
 * OmPointlistOrgPolicy generated by hbm2java
 */
@javax.jdo.annotations.PersistenceCapable(schema = "gemsods", table = "om_pointlist_org_policy", objectIdClass = OmPointlistOrgPolicyPK.class, identityType = IdentityType.APPLICATION)
@javax.jdo.annotations.Queries({ @javax.jdo.annotations.Query(name = "fetch_pointlistorgpolicy_by_user", language = "JPQL", value = "SELECT pointlistOrgPolicy FROM com.wipro.wess.ods.uom.OmPointlistOrgPolicy pointlistOrgPolicy "
        + " JOIN pointlistOrgPolicy.orgId organization WHERE EXISTS "
        + " (SELECT 1 FROM com.wipro.wess.pdm.security.OmPermission permission WHERE permission.site.orgId = organization AND permission IN "
        + " (SELECT "
        + " OmRolesPermissions.permission FROM com.wipro.wess.pdm.security.OmRolesPermissions OmRolesPermissions "
        + " WHERE role IN ( SELECT OmUsersRoles.role FROM com.wipro.wess.pdm.security.OmUsersRoles OmUsersRoles WHERE OmUsersRoles.user.userName = :userName) ) ) ") })
@Audited
@Bookmarkable
@ObjectType("OmPointlistOrgPolicy")
public class OmPointlistOrgPolicy implements java.io.Serializable, InstanceCallbacks {

    /**
     * 
     */
    private static final long serialVersionUID = -5832538578128549113L;

    public MOrganisation orgId;

    public MPointlist pointList;

    private MUnitFamily MUnitFamily;

    private MUnit MUnit;

    private int rowseqId;

    private String description;

    private String datapointtype;

    private String state0;

    private String state1;

    private String changeby;

    private Date changedate;

    private Long sourceId;

    private BigDecimal discardPassLow;

    private BigDecimal discardPassHigh;
    
    private String configUser;

    public OmPointlistOrgPolicy() {
    }

    public OmPointlistOrgPolicy(MPointlist pointList, int rowseqId, String datapointtype, Date changedate) {
        this.pointList = pointList;
        this.rowseqId = rowseqId;
        this.datapointtype = datapointtype;
        this.changedate = changedate;
    }

    public OmPointlistOrgPolicy(MPointlist pointList, MUnitFamily MUnitFamily, MUnit MUnit, int rowseqId,
            String description, String datapointtype, String state0, String state1, String changeby, Date changedate,
            Long sourceId, BigDecimal discardPassLow, BigDecimal discardPassHigh) {
        this.pointList = pointList;
        this.MUnitFamily = MUnitFamily;
        this.MUnit = MUnit;
        this.rowseqId = rowseqId;
        this.description = description;
        this.datapointtype = datapointtype;
        this.state0 = state0;
        this.state1 = state1;
        this.changeby = changeby;
        this.changedate = changedate;
        this.sourceId = sourceId;
        this.discardPassLow = discardPassLow;
        this.discardPassHigh = discardPassHigh;
    }

    @Column(name = "org_id", allowsNull = "false")
    @Persistent(primaryKey = "true")
    @Title
    public MOrganisation getOrgId() {
        return orgId;
    }

    public void setOrgId(MOrganisation orgId) {
        this.orgId = orgId;
    }

    @Columns(value = { @Column(name = "assetclass_code", allowsNull = "false"),
            @Column(name = "point", allowsNull = "false") })
    @Mandatory
    @Persistent(primaryKey = "true")
    @Title
    public MPointlist getPointList() {
        return pointList;
    }

    public void setPointList(MPointlist pointList) {
        this.pointList = pointList;
    }

    @Column(name = "unit_family_id")
    @Hidden(where = Where.ALL_TABLES)
    public MUnitFamily getMUnitFamily() {
        return this.MUnitFamily;
    }

    public void setMUnitFamily(MUnitFamily MUnitFamily) {
        this.MUnitFamily = MUnitFamily;
    }

    @Column(name = "unit_id")
    @Hidden(where = Where.ALL_TABLES)
    public MUnit getMUnit() {
        return this.MUnit;
    }

    public void setMUnit(MUnit MUnit) {
        this.MUnit = MUnit;
    }

    @Column(name = "rowseq_id", allowsNull = "false")
    @Persistent(valueStrategy = IdGeneratorStrategy.INCREMENT)
    @Hidden(where = Where.OBJECT_FORMS)
    public int getRowseqId() {
        return this.rowseqId;
    }

    public void setRowseqId(int rowseqId) {
        this.rowseqId = rowseqId;
    }

    @Column(name = "state_0")
    @Hidden(where = Where.ALL_TABLES)
    public String getState0() {
        return this.state0;
    }

    public void setState0(String state0) {
        this.state0 = state0;
    }

    @Column(name = "state_1")
    @Hidden(where = Where.ALL_TABLES)
    public String getState1() {
        return this.state1;
    }

    public void setState1(String state1) {
        this.state1 = state1;
    }

    @Column(name = "changeby", allowsNull = "false")
    @Hidden(where = Where.OBJECT_FORMS)
    public String getChangeby() {
        return this.changeby;
    }

    public void setChangeby(String changeby) {
        this.changeby = changeby;
    }

    @Column(name = "changedate", allowsNull = "false")
    @Hidden(where = Where.OBJECT_FORMS)
    public Date getChangedate() {
        return this.changedate;
    }

    public void setChangedate(Date changedate) {
        this.changedate = changedate;
    }

    @Column(name = "source_id")
    @Hidden(where = Where.ALL_TABLES)
    public Long getSourceId() {
        return this.sourceId;
    }

    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    @Column(name = "discard_pass_low")
    @Hidden(where = Where.ALL_TABLES)
    public BigDecimal getDiscardPassLow() {
        return this.discardPassLow;
    }

    public void setDiscardPassLow(BigDecimal discardPassLow) {
        this.discardPassLow = discardPassLow;
    }

    @Column(name = "discard_pass_high")
    @Hidden(where = Where.ALL_TABLES)
    public BigDecimal getDiscardPassHigh() {
        return this.discardPassHigh;
    }

    public void setDiscardPassHigh(BigDecimal discardPassHigh) {
        this.discardPassHigh = discardPassHigh;
    }

    @Column(name = "description")
    @Hidden(where = Where.ALL_TABLES)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "datapointtype")
    @Hidden(where = Where.ALL_TABLES)
    public String getDatapointtype() {
        return this.datapointtype;
    }

    public void setDatapointtype(String datapointtype) {
        this.datapointtype = datapointtype;
    }

    @Column(name = "config_user")
    @Hidden(where = Where.EVERYWHERE)
    public String getConfigUser() {
        return configUser;
    }

    public void setConfigUser(String configUser) {
        this.configUser = configUser;
    }
    
    private OrganisationService orgService;

    public void injectOrganisationService(OrganisationService orgService) {
        this.orgService = orgService;
    }

    public List<MOrganisation> choicesOrgId() {
        return this.orgService.listAllOrganisations();
    }

    private DomainObjectContainer container;

    public void injectDomainObjectContainer(final DomainObjectContainer container) {
        this.container = container;
    }

    private MasterConfigurationService masterConfigurationService;

    public void injectMasterConfigurationService(MasterConfigurationService masterConfigurationService) {
        this.masterConfigurationService = masterConfigurationService;
    }

    public List<MPointlist> choicesPointList() {
        return this.masterConfigurationService.listAllPointList();
    }

    public List<MUnitFamily> choicesMUnitFamily() {
        return this.container.allInstances(MUnitFamily.class);
    }

    public List<MUnit> choicesMUnit() {
        return this.container.allInstances(MUnit.class);
    }

    public void jdoPostLoad() {
    }

    public void jdoPreClear() {
    }

    public void jdoPreStore() {
        this.setChangeby(this.container.getUser().getName());
        this.setChangedate(new Date());
        this.setConfigUser(this.container.getUser().getName());
    }

    public void jdoPreDelete() {
    }
    
    private UOMPointListService pointListService;

    public void injectUOMPointListService(UOMPointListService pointListService) {
        this.pointListService = pointListService;
    }

    @Bulk
    @CssClass("x-caution")
    public List<OmPointlistOrgPolicy> delete() {
        this.container.removeIfNotAlready(this);
        this.container.informUser("Deleted " + container.titleOf(this));
        return this.pointListService.listAllUOMPointlistOrgPolicy();

    }

}
