package com.wipro.wess.ods.uom;


// Generated Jan 7, 2014 12:15:31 PM by Hibernate Tools 3.2.2.GA

/**
 * OmPointlistCountryExceptPK generated by hbm2java
 */
public class OmPointlistOrgPolicyAuditPK implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 345657265547985003L;

    public int rowseqId;

    public OmPointlistOrgPolicyAuditPK() {
    }

    public OmPointlistOrgPolicyAuditPK(String key) {
        this.rowseqId = Integer.parseInt(key);
    }

    @Override
    public String toString() {
        return "" + rowseqId;
    }

    public int getRowseqId() {
        return rowseqId;
    }

    public void setRowseqId(int rowseqId) {
        this.rowseqId = rowseqId;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + rowseqId;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        OmPointlistOrgPolicyAuditPK other = (OmPointlistOrgPolicyAuditPK) obj;
        if (rowseqId != other.rowseqId)
            return false;
        return true;
    }

}
