package com.wipro.wess.ods.site;

import java.util.StringTokenizer;

import com.wipro.wess.ods.organisation.OrganisationPK;

// Generated Dec 19, 2013 5:56:26 PM by Hibernate Tools 3.2.2.GA

/**
 * OmAddressId generated by hbm2java
 */
public class OmAddressPK implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7838001947733083151L;

	public String addressId;
	public OrganisationPK orgId;

	public OmAddressPK() {
	}

	public OmAddressPK(String key){
		StringTokenizer token = new StringTokenizer(key, "_");
		this.addressId = token.nextToken();
		this.orgId = new OrganisationPK(token.nextToken());
	}
			
	public OmAddressPK(String addressId, OrganisationPK orgId) {
		this.addressId = addressId;
		this.orgId = orgId;
	}

	public String getAddressId() {
		return this.addressId;
	}

	public void setAddressId(String addressId) {
		this.addressId = addressId;
	}

	public OrganisationPK getOrgId() {
		return this.orgId;
	}

	public void setOrgId(OrganisationPK orgId) {
		this.orgId = orgId;
	}
	

	@Override
	public String toString() {
		return "" + addressId + "_" + orgId.toString();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((addressId == null) ? 0 : addressId.hashCode());
		result = prime * result + ((orgId == null) ? 0 : orgId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OmAddressPK other = (OmAddressPK) obj;
		if (addressId == null) {
			if (other.addressId != null)
				return false;
		} else if (!addressId.equals(other.addressId))
			return false;
		if (orgId == null) {
			if (other.orgId != null)
				return false;
		} else if (!orgId.equals(other.orgId))
			return false;
		return true;
	}



}
