package com.wipro.wess.ods.site;

import java.nio.charset.Charset;
import java.util.StringTokenizer;

import com.google.common.io.BaseEncoding;

// Generated Jan 7, 2014 12:15:31 PM by Hibernate Tools 3.2.2.GA

/**
 * OmSiteExtendedAttrId generated by hbm2java
 */
public class OmSiteExtendedAttrPK implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -8123105866883749859L;

    public OmSitePK site;

    public String paramName;

    public OmSiteExtendedAttrPK() {
    }

    public OmSiteExtendedAttrPK(OmSitePK site, String paramName) {
        this.site = site;
        this.paramName = paramName;
    }

    public OmSiteExtendedAttrPK(String key) {
        StringTokenizer token = new StringTokenizer(decode(key), "~");
        this.site = new OmSitePK(token.nextToken());
        this.paramName = token.nextToken();
    }

    public String getParamName() {
        return this.paramName;
    }

    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    public OmSitePK getSite() {
        return site;
    }

    public void setSite(OmSitePK site) {
        this.site = site;
    }

    @Override
    public String toString() {
        return encode("" + this.site.toString() + "~" + this.paramName);
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((paramName == null) ? 0 : paramName.hashCode());
        result = prime * result + ((site == null) ? 0 : site.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        OmSiteExtendedAttrPK other = (OmSiteExtendedAttrPK) obj;
        if (paramName == null) {
            if (other.paramName != null)
                return false;
        } else if (!paramName.equals(other.paramName))
            return false;
        if (site == null) {
            if (other.site != null)
                return false;
        } else if (!site.equals(other.site))
            return false;
        return true;
    }

    private static String encode(String str) {

        return BaseEncoding.base32().encode(str.getBytes(Charset.forName("UTF-8")));
    }

    private static String decode(String str) {
        return new String(BaseEncoding.base32().decode(str), Charset.forName("UTF-8"));
    }

}
