package com.wipro.wess.ods.site;
// Generated Jan 7, 2014 12:15:31 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * OmUserToSite generated by hbm2java
 */
public class OmUserToSite  implements java.io.Serializable {


     private int recId;
     private String userId;
     private String orgId;
     private String siteId;
     private String status;
     private Date lastmodifiedtime;
     private String lastmodifiedby;
     private String isBaseLoc;

    public OmUserToSite() {
    }

	
    public OmUserToSite(int recId) {
        this.recId = recId;
    }
    public OmUserToSite(int recId, String userId, String orgId, String siteId, String status, Date lastmodifiedtime, String lastmodifiedby, String isBaseLoc) {
       this.recId = recId;
       this.userId = userId;
       this.orgId = orgId;
       this.siteId = siteId;
       this.status = status;
       this.lastmodifiedtime = lastmodifiedtime;
       this.lastmodifiedby = lastmodifiedby;
       this.isBaseLoc = isBaseLoc;
    }
   
    public int getRecId() {
        return this.recId;
    }
    
    public void setRecId(int recId) {
        this.recId = recId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }
    public String getSiteId() {
        return this.siteId;
    }
    
    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getLastmodifiedtime() {
        return this.lastmodifiedtime;
    }
    
    public void setLastmodifiedtime(Date lastmodifiedtime) {
        this.lastmodifiedtime = lastmodifiedtime;
    }
    public String getLastmodifiedby() {
        return this.lastmodifiedby;
    }
    
    public void setLastmodifiedby(String lastmodifiedby) {
        this.lastmodifiedby = lastmodifiedby;
    }
    public String getIsBaseLoc() {
        return this.isBaseLoc;
    }
    
    public void setIsBaseLoc(String isBaseLoc) {
        this.isBaseLoc = isBaseLoc;
    }




}


